[package]
name = "packet_sniffer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.30.0"

[dev-dependencies]
assert_cmd = "2.1.2"
insta = "1.46.3"
predicates = "3.1.4"
